version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: bt-hrms-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - bt_network

  app:
    build:
      args:
        user: btadmin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bt-hrms
    container_name: bt-hrms-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bt_network

  db:
    image: mysql:8.0
    container_name: bt-hrms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - /dockermysqldata:/var/lib/mysql
    networks:
      - bt_network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  bt_network:
    driver: bridge
